package fibe

import (
	"context"
	"encoding/json"
	"net/http"
	"testing"
)

func TestIdempotencyKey_SentInHeader(t *testing.T) {
	var gotKey string
	c, _ := testServer(t, func(w http.ResponseWriter, r *http.Request) {
		gotKey = r.Header.Get("Idempotency-Key")
		w.WriteHeader(201)
		json.NewEncoder(w).Encode(Playground{ID: 1, Name: "test"})
	})

	ctx := WithIdempotencyKey(context.Background(), "my-unique-key")
	c.Playgrounds.Create(ctx, &PlaygroundCreateParams{
		Name:       "test",
		PlayspecID: 1,
	})

	if gotKey != "my-unique-key" {
		t.Errorf("expected Idempotency-Key 'my-unique-key', got %q", gotKey)
	}
}

func TestIdempotencyKey_AutoGeneratedWhenAbsent(t *testing.T) {
	var gotKey string
	c, _ := testServer(t, func(w http.ResponseWriter, r *http.Request) {
		gotKey = r.Header.Get("Idempotency-Key")
		w.WriteHeader(201)
		json.NewEncoder(w).Encode(Playground{ID: 1, Name: "test"})
	})

	c.Playgrounds.Create(context.Background(), &PlaygroundCreateParams{
		Name:       "test",
		PlayspecID: 1,
	})

	if gotKey == "" {
		t.Error("expected auto-generated Idempotency-Key header on POST, got empty")
	}
	if len(gotKey) != 32 {
		t.Errorf("expected 32 hex chars for auto-generated key, got %d: %q", len(gotKey), gotKey)
	}
}

func TestIdempotencyKey_NotSentOnGET(t *testing.T) {
	var gotKey string
	c, _ := testServer(t, func(w http.ResponseWriter, r *http.Request) {
		gotKey = r.Header.Get("Idempotency-Key")
		w.WriteHeader(200)
		json.NewEncoder(w).Encode(Playground{ID: 1, Name: "test"})
	})

	c.Playgrounds.Get(context.Background(), 1)

	if gotKey != "" {
		t.Errorf("expected no Idempotency-Key header on GET, got %q", gotKey)
	}
}

func TestNewIdempotencyKey_Unique(t *testing.T) {
	k1 := NewIdempotencyKey()
	k2 := NewIdempotencyKey()

	if k1 == k2 {
		t.Error("expected unique keys")
	}
	if len(k1) != 32 {
		t.Errorf("expected 32 hex chars, got %d", len(k1))
	}
}
