package main

import (
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/fibegg/sdk/fibe"
	"github.com/spf13/cobra"
)

func artefactsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "artefacts",
		Short: "Manage agent artefacts",
		Long: `Manage files generated by AI Agent iterations.

ARTEFACT CONSTRAINTS:
  - Artefacts securely embed massive context responses, markdown scripts, or JSON configs into the Agent brain without polluting the chat logs.
  - LLM Genies MUST bundle any text output over ~40 lines into an Artefact instead of direct chat messages to keep the session context token window efficient.

SUBCOMMANDS:
  list <agent-id>          List artefacts
  get <agent-id> <id>      Show artefact details
  create <agent-id>        Upload an artefact
  download <agent-id> <id> Download artefact file content`,
	}
	cmd.AddCommand(artListCmd(), artGetCmd(), artCreateCmd(), artDownloadCmd())
	return cmd
}

func artListCmd() *cobra.Command {
	var query, name, agentIDFlag, playgroundID, contentType, createdAfter, createdBefore, sort string
	cmd := &cobra.Command{
		Use: "list [agent-id]", Short: "List artefacts", Args: cobra.MaximumNArgs(1),
		Long: `List artefacts. When agent-id is provided, lists artefacts for that agent.
When omitted, lists all artefacts accessible by the current player.

FILTERS:
  -q, --query           Search across name, description (substring match)
  --name                Filter by name (substring match)
  --agent-id            Filter by agent ID (when listing all)
  --playground-id       Filter by playground ID
  --content-type        Filter by content type

DATE RANGE:
  --created-after       Show items created on or after this date (ISO 8601)
  --created-before      Show items created on or before this date (ISO 8601)

SORTING:
  --sort                Sort results. Format: {column}_{direction}
                        Columns: created_at, name
                        Direction: asc, desc
                        Default: created_at_desc

EXAMPLES:
  fibe artefacts list
  fibe artefacts list 5
  fibe artefacts list -q "report" --sort name_asc
  fibe artefacts list --agent-id 5 --content-type application/pdf -o json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			params := &fibe.ArtefactListParams{}
			if query != "" {
				params.Query = query
			}
			if name != "" {
				params.Name = name
			}
			if playgroundID != "" {
				params.PlaygroundID = playgroundID
			}
			if contentType != "" {
				params.ContentType = contentType
			}
			if createdAfter != "" {
				params.CreatedAfter = createdAfter
			}
			if createdBefore != "" {
				params.CreatedBefore = createdBefore
			}
			if sort != "" {
				params.Sort = sort
			}
			if flagPage > 0 {
				params.Page = flagPage
			}
			if flagPerPage > 0 {
				params.PerPage = flagPerPage
			}

			if len(args) > 0 {
				agentID, _ := strconv.ParseInt(args[0], 10, 64)
				arts, err := c.Artefacts.List(ctx(), agentID, params)
				if err != nil {
					return err
				}
				outputJSON(arts)
			} else {
				if agentIDFlag != "" {
					params.AgentID = agentIDFlag
				}
				arts, err := c.Artefacts.ListAll(ctx(), params)
				if err != nil {
					return err
				}
				outputJSON(arts)
			}
			return nil
		},
	}
	cmd.Flags().StringVarP(&query, "query", "q", "", "Search across name, description")
	cmd.Flags().StringVar(&name, "name", "", "Filter by name (substring)")
	cmd.Flags().StringVar(&agentIDFlag, "agent-id", "", "Filter by agent ID (when listing all)")
	cmd.Flags().StringVar(&playgroundID, "playground-id", "", "Filter by playground ID")
	cmd.Flags().StringVar(&contentType, "content-type", "", "Filter by content type")
	cmd.Flags().StringVar(&createdAfter, "created-after", "", "Filter: created after date (ISO 8601)")
	cmd.Flags().StringVar(&createdBefore, "created-before", "", "Filter: created before date (ISO 8601)")
	cmd.Flags().StringVar(&sort, "sort", "", "Sort order (e.g. created_at_desc)")
	return cmd
}

func artGetCmd() *cobra.Command {
	return &cobra.Command{
		Use: "get <agent-id> <id>", Short: "Show artefact details", Args: cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			agentID, _ := strconv.ParseInt(args[0], 10, 64)
			id, _ := strconv.ParseInt(args[1], 10, 64)
			art, err := c.Artefacts.Get(ctx(), agentID, id)
			if err != nil {
				return err
			}
			outputJSON(art)
			return nil
		},
	}
}

func artCreateCmd() *cobra.Command {
	var name, desc, file string
	cmd := &cobra.Command{
		Use: "create <agent-id>", Short: "Create/upload an artefact", Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			agentID, _ := strconv.ParseInt(args[0], 10, 64)
			params := &fibe.ArtefactCreateParams{Name: name, Description: desc}

			var fileReader io.Reader
			var err error
			var fileName string

			if file != "" {
				if file == "-" {
					fileReader = os.Stdin
					fileName = "stdin"
				} else {
					f, err := os.Open(file)
					if err != nil {
						return err
					}
					defer f.Close()
					fileReader = f
					fileName = file
				}
			} else {
				return fmt.Errorf("required flag --file not provided")
			}

			art, err := c.Artefacts.Create(ctx(), agentID, params, fileReader, fileName)
			if err != nil {
				return err
			}
			if effectiveOutput() != "table" {
				outputJSON(art)
				return nil
			}
			fmt.Printf("Uploaded artefact\n")
			return nil
		},
	}
	cmd.Flags().StringVar(&name, "name", "", "Name")
	cmd.Flags().StringVar(&desc, "description", "", "Description")
	cmd.Flags().StringVar(&file, "file", "", "File to upload (or - for stdin)")
	return cmd
}

func artDownloadCmd() *cobra.Command {
	var to string
	cmd := &cobra.Command{
		Use:   "download <agent-id> <id>",
		Short: "Download an artefact's file content",
		Long: `Download the binary content of an artefact.

REQUIRED FLAGS:
  --to    Output file path (use - for stdout)

EXAMPLES:
  fibe artefacts download 5 100 --to ./report.pdf
  fibe artefacts download 5 100 --to - > report.pdf`,
		Args: cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			agentID, _ := strconv.ParseInt(args[0], 10, 64)
			id, _ := strconv.ParseInt(args[1], 10, 64)
			if to == "" {
				return fmt.Errorf("required field 'to' not set")
			}
			body, filename, contentType, err := c.Artefacts.Download(ctx(), agentID, id)
			if err != nil {
				return err
			}
			defer body.Close()

			var dst io.Writer
			if to == "-" {
				dst = os.Stdout
			} else {
				f, err := os.Create(to)
				if err != nil {
					return fmt.Errorf("create output file: %w", err)
				}
				defer f.Close()
				dst = f
			}

			n, err := io.Copy(dst, body)
			if err != nil {
				return fmt.Errorf("write content: %w", err)
			}
			if to != "-" {
				if filename == "" {
					filename = "(unknown)"
				}
				fmt.Fprintf(os.Stderr, "Wrote %d bytes (filename: %s, content-type: %s) to %s\n", n, filename, contentType, to)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&to, "to", "", "Output file path (required, use - for stdout)")
	return cmd
}

// =============================================================================
// Repo Status: check
// =============================================================================
