package main

import (
	"fmt"
	"io"
	"os"

	"github.com/fibegg/sdk/fibe"
	"github.com/spf13/cobra"
)

func artefactsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "artefacts",
		Aliases: []string{"art"},
		Short:   "Manage agent artefacts",
		Long: `Manage files generated by AI Agent iterations.

ARTEFACT CONSTRAINTS:
  - Artefacts securely embed massive context responses, markdown scripts, or JSON configs into the Agent brain without polluting the chat logs.
  - LLM Genies MUST bundle any text output over ~40 lines into an Artefact instead of direct chat messages to keep the session context token window efficient.

SUBCOMMANDS:
  list <agent-id-or-name>          List artefacts
  get <agent-id-or-name> <id-or-name> Show artefact details
  create <agent-id-or-name>        Upload an artefact
  update <id-or-name>              Update artefact metadata or player-owned body
  download <agent-id-or-name> <id-or-name> Download artefact file content`,
	}
	cmd.AddCommand(artListCmd(), artGetCmd(), artCreateCmd(), artUpdateCmd(), artDownloadCmd())
	return cmd
}

func artListCmd() *cobra.Command {
	var query, name, agentIDFlag, playgroundID, contentType, createdAfter, createdBefore, sort string
	cmd := &cobra.Command{
		Use: "list [agent-id-or-name]", Short: "List artefacts", Args: cobra.MaximumNArgs(1),
		Long: `List artefacts. When agent-id-or-name is provided, lists artefacts for that agent.
When omitted, lists all artefacts accessible by the current player.

FILTERS:
  -q, --query           Search across name, description (substring match)
  --name                Filter by name (substring match)
  --agent-id            Filter by agent ID or name (when listing all)
  --playground-id       Filter by playground ID or name
  --content-type        Filter by content type

DATE RANGE:
  --created-after       Show items created on or after this date (ISO 8601)
  --created-before      Show items created on or before this date (ISO 8601)

SORTING:
  --sort                Sort results. Format: {column}_{direction}
                        Columns: created_at, name
                        Direction: asc, desc
                        Default: created_at_desc

EXAMPLES:
  fibe artefacts list
  fibe artefacts list my-agent
  fibe artefacts list -q "report" --sort name_asc
  fibe artefacts list --agent-id builder --content-type application/pdf -o json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			params := &fibe.ArtefactListParams{}
			if query != "" {
				params.Query = query
			}
			if name != "" {
				params.Name = name
			}
			if playgroundID != "" {
				params.PlaygroundID = playgroundID
			}
			if contentType != "" {
				params.ContentType = contentType
			}
			if createdAfter != "" {
				params.CreatedAfter = createdAfter
			}
			if createdBefore != "" {
				params.CreatedBefore = createdBefore
			}
			if sort != "" {
				params.Sort = sort
			}
			if flagPage > 0 {
				params.Page = flagPage
			}
			if flagPerPage > 0 {
				params.PerPage = flagPerPage
			}

			if len(args) > 0 {
				arts, err := c.Artefacts.ListByAgentIdentifier(ctx(), args[0], params)
				if err != nil {
					return err
				}
				outputJSON(arts)
			} else {
				if agentIDFlag != "" {
					params.AgentID = agentIDFlag
				}
				arts, err := c.Artefacts.ListAll(ctx(), params)
				if err != nil {
					return err
				}
				outputJSON(arts)
			}
			return nil
		},
	}
	cmd.Flags().StringVarP(&query, "query", "q", "", "Search across name, description")
	cmd.Flags().StringVar(&name, "name", "", "Filter by name (substring)")
	cmd.Flags().StringVar(&agentIDFlag, "agent-id", "", "Filter by agent ID or name (when listing all)")
	cmd.Flags().StringVar(&playgroundID, "playground-id", "", "Filter by playground ID or name")
	cmd.Flags().StringVar(&contentType, "content-type", "", "Filter by content type")
	cmd.Flags().StringVar(&createdAfter, "created-after", "", "Filter: created after date (ISO 8601)")
	cmd.Flags().StringVar(&createdBefore, "created-before", "", "Filter: created before date (ISO 8601)")
	cmd.Flags().StringVar(&sort, "sort", "", "Sort order (e.g. created_at_desc)")
	return cmd
}

func artGetCmd() *cobra.Command {
	return &cobra.Command{
		Use: "get <agent-id-or-name> <id-or-name>", Short: "Show artefact details", Args: cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			art, err := c.Artefacts.GetByAgentAndArtefactIdentifier(ctx(), args[0], args[1])
			if err != nil {
				return err
			}
			outputJSON(art)
			return nil
		},
	}
}

func artCreateCmd() *cobra.Command {
	var name, desc, file, body string
	var skill, skillEnabled, plainText bool
	cmd := &cobra.Command{
		Use: "create [agent-id-or-name]", Short: "Create/upload an artefact", Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			params := &fibe.ArtefactCreateParams{Name: name, Description: desc}
			if body != "" {
				params.Body = body
			}
			if cmd.Flags().Changed("plain-text") {
				params.PlainText = &plainText
			}
			if cmd.Flags().Changed("skill") {
				params.Skill = &skill
			}
			if cmd.Flags().Changed("skill-enabled") {
				params.SkillEnabled = &skillEnabled
			}

			var fileReader io.Reader
			var err error
			var fileName string

			if file != "" {
				if file == "-" {
					fileReader = os.Stdin
					fileName = "stdin"
				} else {
					f, err := os.Open(file)
					if err != nil {
						return err
					}
					defer f.Close()
					fileReader = f
					fileName = file
				}
			} else {
				if body == "" {
					return fmt.Errorf("required flag --file or --body not provided")
				}
			}

			var art *fibe.Artefact
			if len(args) > 0 {
				art, err = c.Artefacts.CreateByAgentIdentifier(ctx(), args[0], params, fileReader, fileName)
			} else {
				art, err = c.Artefacts.CreateOwned(ctx(), params, fileReader, fileName)
			}
			if err != nil {
				return err
			}
			if effectiveOutput() != "table" {
				outputJSON(art)
				return nil
			}
			fmt.Printf("Uploaded artefact\n")
			return nil
		},
	}
	cmd.Flags().StringVar(&name, "name", "", "Name")
	cmd.Flags().StringVar(&desc, "description", "", "Description")
	cmd.Flags().StringVar(&file, "file", "", "File to upload (or - for stdin)")
	cmd.Flags().StringVar(&body, "body", "", "Inline artefact body")
	cmd.Flags().BoolVar(&plainText, "plain-text", false, "Render body as plain text")
	cmd.Flags().BoolVar(&skill, "skill", false, "Expose this artefact as a skill")
	cmd.Flags().BoolVar(&skillEnabled, "skill-enabled", false, "Enable this artefact skill by default")
	return cmd
}

func artUpdateCmd() *cobra.Command {
	var name, desc, body string
	var skill, skillEnabled, plainText bool
	cmd := &cobra.Command{
		Use: "update <id-or-name>", Short: "Update artefact metadata or body", Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			params := &fibe.ArtefactUpdateParams{}
			if cmd.Flags().Changed("name") {
				params.Name = &name
			}
			if cmd.Flags().Changed("description") {
				params.Description = &desc
			}
			if cmd.Flags().Changed("body") {
				params.Body = &body
			}
			if cmd.Flags().Changed("plain-text") {
				params.PlainText = &plainText
			}
			if cmd.Flags().Changed("skill") {
				params.Skill = &skill
			}
			if cmd.Flags().Changed("skill-enabled") {
				params.SkillEnabled = &skillEnabled
			}
			art, err := c.Artefacts.UpdateByIdentifier(ctx(), args[0], params)
			if err != nil {
				return err
			}
			outputJSON(art)
			return nil
		},
	}
	cmd.Flags().StringVar(&name, "name", "", "Name")
	cmd.Flags().StringVar(&desc, "description", "", "Description")
	cmd.Flags().StringVar(&body, "body", "", "Inline artefact body")
	cmd.Flags().BoolVar(&plainText, "plain-text", false, "Render body as plain text")
	cmd.Flags().BoolVar(&skill, "skill", false, "Expose this artefact as a skill")
	cmd.Flags().BoolVar(&skillEnabled, "skill-enabled", false, "Enable this artefact skill by default")
	return cmd
}

func artDownloadCmd() *cobra.Command {
	var to string
	cmd := &cobra.Command{
		Use:   "download <agent-id-or-name> <id-or-name>",
		Short: "Download an artefact's file content",
		Long: `Download the binary content of an artefact.

REQUIRED FLAGS:
  --to    Output file path (use - for stdout)

EXAMPLES:
  fibe artefacts download my-agent report --to ./report.pdf
  fibe artefacts download my-agent report --to - > report.pdf`,
		Args: cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			c := newClient()
			if to == "" {
				return fmt.Errorf("required field 'to' not set")
			}
			body, filename, contentType, err := c.Artefacts.DownloadByAgentAndArtefactIdentifier(ctx(), args[0], args[1])
			if err != nil {
				return err
			}
			defer body.Close()

			var dst io.Writer
			if to == "-" {
				dst = os.Stdout
			} else {
				f, err := os.Create(to)
				if err != nil {
					return fmt.Errorf("create output file: %w", err)
				}
				defer f.Close()
				dst = f
			}

			n, err := io.Copy(dst, body)
			if err != nil {
				return fmt.Errorf("write content: %w", err)
			}
			if to != "-" {
				if filename == "" {
					filename = "(unknown)"
				}
				fmt.Fprintf(os.Stderr, "Wrote %d bytes (filename: %s, content-type: %s) to %s\n", n, filename, contentType, to)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&to, "to", "", "Output file path (required, use - for stdout)")
	return cmd
}

// =============================================================================
// Repo Status: check
// =============================================================================
